### PR TITLE
Fixes wrong names in some methods, VPC support and adds Create<Resource> methods

### PR DESCRIPTION
**Pull request by joseribes**
CreateBatchPrediction, CreateAnomalyScore were bad spelled.
CreatePrediction is an alternative to Create method for predicitions.
Removes extra space.

### CODE REVIEW

**Comment by osroca** [comment]
@joseribes if `CreatePrediction` is an alias of the former `Create`, wouldn't be useful to have the same for the other "prediction" resources (Centroid, AnomalyScore, BatchPrediction, ...) ?

**Comment by joseribes** [comment]
El 30/06/2015 a las 10:11, Oscar Rovira escribió:
>
> @joseribes <https://github.com/joseribes> if |CreatePrediction| is an 
> alias of the former |Create|, wouldn't be useful to have the same for 
> the other "prediction" resources (Centroid, AnomalyScore, 
> BatchPrediction, ...) ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bigmlcom/bigml-csharp/pull/20#issuecomment-117050740>.
>

Yes. To unify that makes sense.


The resources I built from the begin I only write the createXXX method, 
but for the originals: source, dataset, model and prediction all of them 
had a Create(params) method. I thought that this can be not very clear 
for developers and began to create both methods in some resources. 
Finally only exists CreateXXX.

I keep originals methods on to make backward compatible. We can remove 
the Create(params) methods or define one for each kind of resources.

**Comment by osroca** [comment]
It would be great if you could add them in this PR and if do you prefer, mark the deprecated methods (`Create`) as `Obsolete`.

**Comment by joseribes** [comment]
El 30/06/2015 a las 17:49, Oscar Rovira escribió:
>
> It would be great if you could add them in this PR and if do you 
> prefer, mark the deprecated methods (|Create|) as |Obsolete|.
>
Ok. I would include the VPCs support too.
The url is the unique chage, right?

https://bigml.io/{dev/}andromeda/{resource}?username={username};api_key={apiKey}

¿is replaced by
https://{VPCsubdomain}bigml.io/{dev/}andromeda/{resource}?username={username};api_key={apiKey}
?

**Comment by osroca** [comment]
hmmm, good point! it would be better support something like `BIGML_DOMAIN` as the Python bindings does. If the VPC is actually an on-premise deployment (behind the firewall) we may find that the API service is running in a totally different host and port (ie: `api-bml.intranetdomain.net:8833`).

**Comment by joseribes** [comment]
Ready to merge. Tested with horizon enviroment as "VPC"

**Comment by osroca** [comment]
@joseribes you mentioned that you have written a couple of gists with samples on how to use the bindings, why do you not create a `samples.md` doc? in it you could list the samples and link to the gist.

**Comment by joseribes** [comment]
El 02/07/2015 a las 13:46, Oscar Rovira escribió:
>
> @joseribes <https://github.com/joseribes> you mentioned that you have 
> written a couple of gists with samples on how to use the bindings, why 
> do you not create a |samples.md| doc? in it you could list the samples 
> and link to the gist.
>
And I'll upload my local folder "gists" with the current examples.

**Pull request merged**
